### ISSUE TITLE
How to build global flags such as log level?

### ISSUE THREAD

**Issue by kevbook** [drizzle-team/brocli#1]

**Comment by kevbook** [comment]
I know there are no global flags, it's a feature request. I can do a PR or fork, you decide.

**Comment by Sukairo-02** [comment]
I don't see how global flags would work with current api without breaking type-safety

**Comment by Sukairo-02** [comment]
[v0.11.0](https://github.com/drizzle-team/brocli/releases/tag/0.11.0) introduces global flags, however available not on commands, but on `hook` to preserve type safety.

**Comment by robingenz** [comment]
@Sukairo-02 Is there a chance to also get support for commands?
